name: Build Imagine Sandbox Template
description: Builds the Imagine Sandbox template
author: Ariel Weinberger

branding:
  icon: heart
  color: red

inputs:
  sandboxProviderApiKey:
    description: API key for the sandbox provider
    required: true
  dockerTags:
    description: Docker metadata tags (newline-separated, from docker/metadata-action output)
    required: true
  cpuCount:
    description: The number of CPUs to use
    required: false
    default: '4'
  memoryMB:
    description: The amount of memory to use
    required: false
    default: '2048'

outputs:
  aliases:
    description: The aliases of the built templates
    value: ${{ steps.build.outputs.aliases }}

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: '1.3.1'

    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bun install --frozen-lockfile

    - name: Build templates
      id: build
      shell: bash
      env:
        INPUT_SANDBOXPROVIDERAPIKEY: ${{ inputs.sandboxProviderApiKey }}
        INPUT_DOCKERTAGS: ${{ inputs.dockerTags }}
        INPUT_CPUCOUNT: ${{ inputs.cpuCount }}
        INPUT_MEMORYMB: ${{ inputs.memoryMB }}
      run: bun run ${{ github.action_path }}/src/index.ts
