name: Build Imagine Sandbox Template
description: Builds the Imagine Sandbox template
author: Ariel Weinberger

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  sandboxProviderApiKey:
    description: API key for the sandbox provider
    required: true
  dockerTags:
    description:
      Docker metadata tags (newline-separated, from docker/metadata-action
      output)
    required: true
  cpuCount:
    description: The number of CPUs to use
    required: false
    default: '4'
  memoryMB:
    description: The amount of memory to use
    required: false
    default: '2048'

# Define your outputs here.
outputs:
  aliases:
    description: The aliases of the built templates

runs:
  using: node24
  main: dist/index.js
